swagger: '2.0'
info:
  description: This is the Lydia API
  version: 1.0.0
  title: Lydia API
  # put the contact info for your development or API team
  contact:
    email: gr-lydia@wpi.edu

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: consumers
  description: Operations available to regular consumers

paths:
  /upload-segment:
    post:
      tags:
      - consumers
      summary: Requests to uploads a video segment
      operationId: uploadVideoSegment
      description: Requests to upload a video segment
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: UploadVideoSegmentRequest
        description: Uploads a video segment
        schema:
          $ref: '#/definitions/uploadVideoSegment'
      responses:
        200:
          description: video segment uploaded
        400:
          description: invalid video segment
  /delete-segment:
    post:
      tags:
      - consumers
      summary: request to delete a video segment
      operationId: deleteVideoSegment
      description: Requests to delete a video segment by id.
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: DeleteVideoSegment
        description: Delete a video segment
        schema:
          $ref: '#/definitions/deleteVideoSegment'
      responses:
        200:
          description: video segment deleted
        400:
          description: invalid video segment
        409:
          description: unable to delete video segement   
  /list-segments:
    get:
      tags:
      - consumers
      summary: request a list of all video segments
      operationId: listVideoSegments
      description: Returns a list of all video segments
      produces:
      - application/json
      responses:
        200:
          description: list of video segments returned
        400: 
          description: unable to get list of video segments
  /search-segments:
    get:
      tags:
      - consumers
      summary: searches for a specific segment
      operationId: searchVideoSegments
      description: Returns the found video segment
      produces:
      - application/json
      responses:
        200:
          description: found video segment returned
        409:
          description: unable to find video segment
  /create-playlist:
  /delete-playlist:
  /list-playlist:
  /remove-from-playlist:
  /add-to-playlist:
  /mark-unmark-local:
  /register-site:
     post:
        tags:
        - admins
        summary: registers a remote site
        description: Registers a connection to a remote site
        operationId: requestConnect
        consumes:
         - application/json
        produces:
        - application/json
        parameters:
         - in: url
           name: RegisterSite
           description: Registers a connection to a remote site
           required: true
           schema:
             $ref: '#/definitions/RegisterSite'
        responses:
            200:
               description: connection established
  /unregister-site:
  /list-sites:
   
      
definitions:
  InventoryItem:
    type: object
    required:
    - id
    - name
    - manufacturer
    - releaseDate
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: Widget Adapter
      releaseDate:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
      manufacturer:
        $ref: '#/definitions/Manufacturer'
  Manufacturer:
    required:
    - name
    properties:
      name:
        type: string
        example: ACME Corporation
      homePage:
        type: string
        format: url
        example:  https://www.acme-corp.com
      phone:
        type: string
        example: 408-867-5309
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /cs3733Lydia/Lydia/1.0.0
schemes:
 - https