swagger: '2.0'
info:
  description: This is the Lydia API
  version: 1.0.0
  title: Lydia API
  # put the contact info for your development or API team
  contact:
    email: gr-lydia@wpi.edu

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: consumers
  description: Operations available to regular consumers

paths:
  /upload-segment:
  /delete-segment:
  /list-segments:
  /search-segments:
  /create-playlist:
  /delete-playlist:
  /list-playlist:
  /remove-from-playlist:
  /add-to-playlist:
  /mark-unmark-local:
  /register-site:
  /unregister-site:
  /list-sites:
   
      
definitions:
  InventoryItem:
    type: object
    required:
    - id
    - name
    - manufacturer
    - releaseDate
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: Widget Adapter
      releaseDate:
        type: string
        format: date-time
        example: 2016-08-29T09:12:33.001Z
      manufacturer:
        $ref: '#/definitions/Manufacturer'
  Manufacturer:
    required:
    - name
    properties:
      name:
        type: string
        example: ACME Corporation
      homePage:
        type: string
        format: url
        example:  https://www.acme-corp.com
      phone:
        type: string
        example: 408-867-5309
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /cs3733Lydia/Lydia/1.0.0
schemes:
 - https